# Generated by Django 4.1 on 2025-10-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='foto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
